# Store kubeconfig credentials. Credential Type is already created.

  - name: Create cluster Token Credential
    ansible.controller.credential:
      name: "{{ cred_cluster_name }}"
      organization: "Default"
      credential_type: "OpenShift or Kubernetes API Bearer Token"
      inputs: 
        bearer_token: "{{ cred_cluster_token }}"
        host: "{{ cred_cluster_api }}"
      state: present #Desired state of the resource. exists will not modify the resource if it is present.
      update_secrets: true #Update the secret if it already exists.
      validate_certs: false
    when:
      - cred_cluster_token is defined
      - cred_cluster_api is defined
      - cred_cluster_name is defined
