# Store kubeconfig credentials. Credential Type is already created.

  - name: Create cluster Credential
    ansible.controller.credential:
      #controller_host: "{{ CONTROLLER_HOST }}"
      #controller_username: "{{ CONTROLLER_USERNAME }}"
      #controller_password: "{{ CONTROLLER_PASSWORD }}"
      name: "{{ cluster }}"
      organization: "Default"
      credential_type: "Cluster Kubeconfig File"
      inputs: 
        kubeconfig: "{{ kubeconfig_data }}"
        #ssh_key_data: "{{ lookup('file', kubeconfig }}"
      state: present
      validate_certs: false
