# Store kubeconfig credentials. Credential Type is already created.

  - name: Create cluster Token Credential
    ansible.controller.credential:
      name: "{{ cluster }}"
      organization: "Default"
      credential_type: "OpenShift or Kubernetes API Bearer Token"
      inputs: 
        bearer_token: "{{ cluster_token }}"
        host: "{{ cluster_api }}"
      state: present
      validate_certs: false
    when:
      - cluster_token is defined
      - cluster_api is defined
      - cluster is defined
