# This file contains tasks to process a single item from kubeconfig_secret_info_raw.results.
# 'item' here refers to the current result object from the loop in the parent playbook.

  - name: Deploy ns application to the cluster
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
      state: present
      api_version: v1
      kind: Namespace
      name: emojivoto
    register: result
    until: result.failed != true
    retries: 5
    delay: 10

  - name: Deploy web application to the cluster
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
      state: present
      src: "{{ item }}"
    register: result
    until: result.failed != true
    retries: 30
    delay: 10
    loop:
      - https://raw.githubusercontent.com/alosadagrande/eda-tests/refs/heads/main/emojivoto/deployment/web.yml
      - https://raw.githubusercontent.com/alosadagrande/eda-tests/refs/heads/main/emojivoto/deployment/emoji.yml
      - https://raw.githubusercontent.com/alosadagrande/eda-tests/refs/heads/main/emojivoto/deployment/voting.yml

  - name: Expose application to the internet
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
      state: present
      definition:
        apiVersion: "route.openshift.io/v1"
        kind: Route
        metadata:
          name: web
          namespace: emojivoto
        spec:
          port:
            targetPort: http
          to:
            kind: Service
            name: web-svc
            weight: 100
          wildcardPolicy: None

  - name: The application is ready 
    kubernetes.core.k8s_info:
      kubeconfig: "{{ kubeconfig }}"
      api_version: "route.openshift.io/v1"
      kind: Route
      name: web
      namespace: emojivoto
    register: emojivoto_route
    retries: 6 
    delay: 10
    until:
      - emojivoto_route is defined
      - emojivoto_route.resources | length > 0
      - emojivoto_route.resources[0].status is defined
      - emojivoto_route.resources[0].status.ingress[0].conditions[0].status == "True"
      - emojivoto_route.resources[0].status.ingress[0].host is defined

  - name: Application URL
    ansible.builtin.debug: 
      msg: "The application is ready at {{ emojivoto_route.resources[0].status.ingress[0].host }}" 

  - community.general.slack:
      token: "{{ slack_token }}"
      msg: ":white_check_mark: The workload has been deployed successfully and can be accessed at {{ emojivoto_route.resources[0].status.ingress[0].host }}" 
      channel: '#infra-notifications'
      icon_emoji: ':white_check_mark:'
