# This file is used to extract the kubeconfig from the cluster.

- name: Debug kubeconfig extraction
  ansible.builtin.debug:
    msg: "Extracting kubeconfig for cluster {{ cluster_name }} using kubeconfig: {{ hub_kubeconfig | default(kubeconfig_file) }}"

- name: Get cluster kubeconfig secret
  kubernetes.core.k8s_info:
    kubeconfig: "{{ hub_kubeconfig | default(kubeconfig_file) }}"
    api_version: v1
    kind: Secret
    name: "{{ cluster_name }}-admin-kubeconfig"
    namespace: "{{ cluster_name }}"
  register: kubeconfig_secret_result

- name: Validate kubeconfig secret exists
  ansible.builtin.fail:
    msg: "Kubeconfig secret for cluster {{ cluster_name }} not found or missing 'kubeconfig' key"
  when:
    - kubeconfig_secret_result.resources | default([]) | length == 0 or
      not (kubeconfig_secret_result.resources[0].data | default({})).kubeconfig is defined

- name: Extract kubeconfig content
  ansible.builtin.set_fact:
    extracted_kubeconfig: "{{ kubeconfig_secret_result.resources[0].data.kubeconfig | b64decode }}"
  no_log: true
  when:
    - kubeconfig_secret_result.resources | default([]) | length > 0
    - (kubeconfig_secret_result.resources[0].data | default({})).kubeconfig is defined

- name: Debug kubeconfig extraction result
  ansible.builtin.debug:
    msg: "Successfully extracted kubeconfig for cluster {{ cluster_name }}"
  when: extracted_kubeconfig is defined 