# This file contains tasks to process a single item from kubeconfig_secret_info_raw.results.
# 'item' here refers to the current result object from the loop in the parent playbook.

  - name: Provisioning of cluster {{ item.cguName }} finished successfully
    ansible.builtin.debug:
      msg: |
        "A new TALM event is received at {{ ansible_date_time.iso8601 }}:
        The configuration stage for cluster {{ item.cguName }} managed by the {{ item.leafHubName }} hub cluster SUCCEEDED. The cluster is ready to run workloads."

  - name: Get leaf hub cluster and set 'hub_cluster'
    # Este set_fact se ejecutará por cada elemento del loop anterior que cumplió las condiciones 'when'
    ansible.builtin.set_fact:
      hub_cluster: "{{ item.leafHubName }}"
    when: item.leafHubName != "local-cluster"

  - name: Get leaf hub cluster and set 'hub_cluster'
    # Este set_fact se ejecutará por cada elemento del loop anterior que cumplió las condiciones 'when'
    ansible.builtin.set_fact:
      hub_cluster: "local_cluster"
    when: item.leafHubName == "local-cluster"

  - name: Asignar el valor de item.cguName a la variable 'cluster'
    # Este set_fact se ejecutará por cada elemento del loop anterior que cumplió las condiciones 'when'
    ansible.builtin.set_fact:
      cluster: "{{ item.cguName }}" 

  - name: path to the kubeconfig file
    kubernetes.core.k8s_info:
      kubeconfig: "{{ lookup('ansible.builtin.vars', 'kube_hub_' + hub_cluster) }}"
      #kubeconfig: "{{ kube_local_cluster }}"
      api_version: v1
      kind: Secret
      name: "{{ cluster }}-admin-kubeconfig"
      namespace: "{{ cluster }}"
    register: kubeconfig_secret_info

  - name: Mostrar ruta del kubeconfig extraído
    ansible.builtin.debug: 
      var: kubeconfig_secret_info

  - name: Verificar si el Secret existe y contiene el 'kubeconfig'
    ansible.builtin.fail:
      msg: "El Secret del cluster {{ cluster }} no se encontró o no contiene la clave 'kubeconfig'."
    when:
      - not kubeconfig_secret_info.resources | default([])
      - not (kubeconfig_secret_info.resources[0].data | default({})).kubeconfig is defined

  - name: Decodificar y guardar el kubeconfig en un archivo
    ansible.builtin.copy:
      content: "{{ kubeconfig_secret_info.resources[0].data.kubeconfig | b64decode }}"
      dest: "{{ kubeconfig_output_path }}"
      mode: '0600' # Permisos restrictivos para el archivo kubeconfig
    no_log: true # Evita que el contenido del kubeconfig se imprima en la salida del log
    when: (kubeconfig_secret_info.resources[0].data | default({})).kubeconfig is defined

  - name: Mostrar ruta del kubeconfig extraído
    ansible.builtin.debug:
      msg: "El kubeconfig se ha extraído y guardado en: {{ kubeconfig_output_path }}"
    when: (kubeconfig_secret_info.resources[0].data | default({})).kubeconfig is defined

  - name: Set KUBECONFIG environment variable
    set_fact:
      kubeconfig: "{{ kubeconfig_output_path }}"
      kubeconfig_data: "{{ kubeconfig_secret_info.resources[0].data.kubeconfig | b64decode }}"

  - name: Deploy the emojivoto app
    ansible.builtin.include_tasks: create_credential_kubeconfig.yaml # Reference the new file
    when:
      - kubeconfig_data is defined

  - name: Deploy the emojivoto app
    ansible.builtin.include_tasks: deploy_emojivoto_kubeconfig.yaml # Reference the new file
    when:
      - kubeconfig is defined
