# This file is used to store the kubeconfig in the secret store.

- name: Create/update cluster Kubeconfig Credential
  ansible.controller.credential:
    name: "{{ cred_cluster_name }}"
    organization: "{{ aap_organization | default('Default') }}"
    credential_type: "{{ aap_credential_type | default('Cluster Kubeconfig File') }}"
    inputs: 
      kubeconfig_file: "{{ cred_kubeconfig_data }}"
    state: present
    update_secrets: true
    validate_certs: "{{ validate_certs | default(false) }}"
  register: credential_result
  
- name: Display kubeconfig credential creation result
  ansible.builtin.debug:
    msg: "Kubeconfig credential '{{ cred_cluster_name }}' {{ 'updated' if credential_result.changed else 'already exists' }}" 