# This file is used to store the token in the secret store.

- name: Create/update cluster Token Credential
  ansible.controller.credential:
    name: "{{ cred_cluster_name }}"
    organization: "{{ aap_organization | default('Default') }}"
    credential_type: "{{ aap_credential_type | default('OpenShift or Kubernetes API Bearer Token') }}"
    inputs: 
      bearer_token: "{{ cred_cluster_token }}"
      host: "{{ cred_cluster_api }}"
    state: present
    update_secrets: true
    validate_certs: "{{ validate_certs | default(false) }}"
  register: credential_result
  
- name: Display credential creation result
  ansible.builtin.debug:
    msg: "Credential '{{ cred_cluster_name }}' {{ 'updated' if credential_result.changed else 'already exists' }}"
