apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-svc
  namespace: emojivoto
spec:
  host: emojivoto.apps.sno-worker-01.inbound-int.se-lab.eng.rdu2.dc.redhat.com
  port:
    targetPort: http
  to:
    kind: Service
    name: web-svc
    weight: 100
  wildcardPolicy: None
