- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ConfigMap
        namespace: default
        kubeconfig: /home/runner/.kube/config
  rules:
    - name: Notify
      condition: event.type is defined
      #condition: event.type == "ADDED"
      action:
        debug:
        run_playbook:
          name: k8-eda-demo-playbook.yaml
          set_facts: true
