- name: Read messages from a kafka topic from RHACM
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: "{{ HOST }}"
        port: 443
        topic: "{{ TOPIC }}"
        check_hostname: false
        cafile: "{{ eda.filename.ca_cert }}"
        certfile: "{{ eda.filename.client_cert }}"
        keyfile: "{{ eda.filename.client_key }}"
        verify_mode: CERT_NONE
  rules:
    - name: Notify
      condition: event.body is defined
      actions:
        - run_job_template:
            name: "Slack Notification TALM event"
            organization: Default
        - debug:
            msg: "Printing {{ event.body }}"
#      condition: event.body is selectattr('reason', 'in', 'CguSuccess') and event.body is selectattr('cguName', 'in', "{{ CLUSTER }}") and event.body is selectattr('message', 'in', 'ClusterGroupUpgrade {{ CLUSTER }} succeeded remediating policies')
#      action:
#        debug:
