- hosts: localhost
  connection: local
  vars:
    target_clusters:
      - sno-worker-01
      - sno-worker-02
      - 5g-deployment-lab
  tasks:
      - community.general.slack:
          token: "{{ slack_token }}"
          msg: |
            "A new TALM event is received at {{ ansible_date_time.iso8601 }}:
            The configuration stage for cluster {{ item.cguName }} managed by the {{ item.leafHubName }} hub cluster SUCCEEDED. The cluster is ready to run workloads. Deployment of the emojivote application is started"
          channel: '#infra-notifications'
          icon_emoji: ':rotating_light:'
        loop: "{{ ansible_eda.event.body }}"
        when:
          - item.eventAnnotations['cgu.openshift.io/event-type'] == "global"
          - item.cguName in target_clusters
          - item.reason == "CguSuccess"

#      - name: Create the kubeconfig path
#        ansible.builtin.set_fact:
#          kubeconfig_tmp: "{{ 'kube_' + item.cguName | replace('-','_') }}"
#        loop: "{{ ansible_eda.event.body }}"
#        when:
#          - item.eventAnnotations['cgu.openshift.io/event-type'] == "global"
#          - item.cguName in target_clusters
#          - item.reason == "CguSuccess"
#
#      - name: name of the kubeconfig
#        ansible.builtin.debug:
#          var:  kubeconfig_tmp

      - name: path to the kubeconfig file
        ansible.builtin.set_fact:
          kubeconfig: "{{ lookup('ansible.builtin.vars', 'kube_' + item.cguName | replace('-','_')) }}"
        loop: "{{ ansible_eda.event.body }}"
        when: 
          - item.eventAnnotations['cgu.openshift.io/event-type'] == "global"
          - item.cguName in target_clusters
          - item.reason == "CguSuccess"

      - name: Debug path to kubeconfig
        ansible.builtin.debug:
          var: kubeconfig

      - name: Deploy ns application to the cluster
        kubernetes.core.k8s:
          kubeconfig: "{{ kubeconfig }}"
          state: present
          api_version: v1
          kind: Namespace
          name: alosadatest
          #src: https://raw.githubusercontent.com/BuoyantIO/emojivoto/refs/heads/main/kustomize/deployment/ns.yml
        register: result
        until: result.failed != true
        retries: 5
        delay: 10

       
      #when: {{ ansible_eda.event | json_query('body[?reason==`cguSuccess`].message }}

