- hosts: localhost
  connection: local
  vars:
    kubeconfig_output_path: "/tmp/kubeconfig-extracted.yaml" # Ruta donde se guardará el kubeconfig
    deploy_emoji: False
  tasks:
      - name: Process every result and extract the kubeconfig # This task's name for the include
        ansible.builtin.include_tasks: process_kubeconfig.yaml # Reference the new file
        loop: "{{ ansible_eda.event.body }}"
        when:
          - item.eventAnnotations['cgu.openshift.io/event-type'] == "cluster"
          - item.eventAnnotations is defined # Asegura que el diccionario exista
          - item.eventAnnotations['cgu.openshift.io/cluster-name'] is defined
          - item.eventAnnotations['cgu.openshift.io/cluster-name'] == item.cguName) # Asegura que la clave exista y compara
          - item.reason == "CguSuccess"
