- hosts: localhost
  connection: local
  vars:
    target_reasons:
      - CguSuccess
      - CguTimedout
      - CguValidationFailure
  tasks:
    - community.general.slack:
        token: "{{ slack_token }}"
        msg: | 
          "A new TALM event is received at {{ ansible_date_time.iso8601 }}:
          The configuration stage for cluster {{ item.cguName }} managed by the {{ item.leafHubName }} hub cluster FAILED with status {{ item.reason }} and message {{ item.message }}."
        channel: '#infra-notifications'
        icon_emoji: ':rotating_light:'
      loop: "{{ ansible_eda.event.body }}"
      when:
        - item.reason == "CguTimedout" or item.reason == "CguValidationFailure"
        - item.eventAnnotations['cgu.openshift.io/event-type'] == "global"
      #when: {{ ansible_eda.event | json_query('body[?reason==`cguSuccess`].message }}

    - block:
      - community.general.slack:
          token: "{{ slack_token }}"
          msg: |
            "A new TALM event is received at {{ ansible_date_time.iso8601 }}:
            The configuration stage for cluster {{ item.cguName }} managed by the {{ item.leafHubName }} hub cluster SUCCEEDED. The cluster is ready to run workloads. Deployment of the emojivote application is started"
          channel: '#infra-notifications'
          icon_emoji: ':rotating_light:'

#      - builtin.set_fact:
#          ocp_cluster_name: "{{ item.cguName }}"

      - name: Deploy application to the cluster
        kubernetes.core.k8s:
          kubeconfig: "{{ item.cguName }}"
          state: present
          src: https://raw.githubusercontent.com/BuoyantIO/emojivoto/refs/heads/main/kustomize/deployment/ns.yml
        register: result
        until: result.failed != true
        retries: 5
        delay: 60
      loop: "{{ ansible_eda.event.body }}"
      when:
        - item.reason == "Success"
        - item.eventAnnotations['cgu.openshift.io/event-type'] == "global"

       
      #when: {{ ansible_eda.event | json_query('body[?reason==`cguSuccess`].message }}

