- hosts: localhost
  connection: local
  tasks:
    - community.general.slack:
        token: "{{ slack_token }}"
        msg: "Event received: {{ ansible_eda.event.body }}"
        channel: '#infra-notifications'
