- hosts: localhost
  connection: local
  vars:
    kubeconfig_output_path: "/tmp/kubeconfig-extracted.yaml" # Path where the target cluster kubeconfig will be saved
    kubeconfig_file: "{{ ansible_env.HOME }}/.kube/config" # Default kubeconfig file path
    managedsa: automation # ManagedSA name to be used to obtain the token
  tasks:
      - name: Process every result and extract the managedsa token
        ansible.builtin.include_tasks: tasks/extract_cluster_token.yaml
        loop: "{{ ansible_eda.event.body }}"
        when:
          - item.eventAnnotations['cgu.openshift.io/event-type'] == "cluster"
          - item.eventAnnotations is defined # Verifies that the dictionary exists
          - item.eventAnnotations['cgu.openshift.io/cluster-name'] == item.cguName # Verifies that the key exists and compares
          - item.eventAnnotations['cgu.openshift.io/cluster-name'] is defined
          - item.reason == "CguSuccess"
