# This playbook is executed when a cluster is ready.
# It extracts the token from the cluster and store it in the secret store.
# It also deploys the emojivoto application to the cluster as action.
# It handles both global hub and leaf hub scenarios.
- hosts: localhost
  connection: local
  vars:
    kubeconfig_file: "{{ ansible_env.HOME }}/.kube/config"
    managedsa: "{{ managedsa_name | default('automation') }}"
    # AAP Configuration (can be overridden)
    aap_organization: "{{ aap_org | default('Default') }}"
    aap_credential_type: "OpenShift or Kubernetes API Bearer Token"
    
  tasks:
    - name: Process every result and extract the managedsa token
      ansible.builtin.include_tasks: tasks/process_cluster_events_token.yaml
      loop: "{{ ansible_eda.event.body }}"
      loop_control:
        label: "{{ item.cguName | default('invalid-event') }}"
      when:
        - item.eventAnnotations['cgu.openshift.io/event-type'] == "cluster"
        - item.eventAnnotations is defined # Verifies that the dictionary exists
        - item.eventAnnotations['cgu.openshift.io/cluster-name'] == item.cguName # Verifies that the key exists and compares
        - item.eventAnnotations['cgu.openshift.io/cluster-name'] is defined
        - item.eventNamespace == "ztp-install"
        - item.reason == "CguSuccess" 