# This playbook is executed when a cluster is ready.
# It extracts the kubeconfig from the cluster and store it in the secret store.
# It also deploys the emojivoto application to the cluster as action.
# It uses the kubeconfig file to authenticate to the cluster.
- hosts: localhost
  connection: local
  vars:
    # Configuration variables
    kubeconfig_cluster_output_path: "/tmp/cluster-kubeconfig.yaml"
    kubeconfig_leafhub_output_path: "/tmp/leaf-hub-kubeconfig.yaml"
    kubeconfig_file: "{{ ansible_env.HOME }}/.kube/config"
    managedsa: "{{ managedsa_name | default('automation') }}"
    # AAP Configuration (can be overridden)
    aap_organization: "{{ aap_org | default('Default') }}"
    aap_credential_type: "Cluster Kubeconfig File"

  tasks:
    - name: Process every result and extract the kubeconfig
      ansible.builtin.include_tasks: tasks/process_cluster_events_kubeconfig.yaml
      loop: "{{ ansible_eda.event.body }}"
      when:
        - item.eventAnnotations['cgu.openshift.io/event-type'] == "cluster"
        - item.eventAnnotations is defined # Verifies that the dictionary exists
        - item.eventAnnotations['cgu.openshift.io/cluster-name'] == item.cguName # Verifies that the key exists and compares
        - item.eventAnnotations['cgu.openshift.io/cluster-name'] is defined
        - item.reason == "CguSuccess"
