# Optimized version - validate first, process later
- hosts: localhost
  connection: local
  vars:
    # Only static, cheap variables here
    kubeconfig_file: "{{ ansible_env.HOME }}/.kube/config"
    aap_organization: "{{ aap_org | default('Default') }}"
    aap_credential_type: "Cluster Kubeconfig File"
    temp_base_dir: "/tmp/ansible-talm"

  tasks:
    - name: Ensure temp directory exists (once)
      ansible.builtin.file:
        path: "{{ temp_base_dir }}"
        state: directory
        mode: '0700'
      run_once: true
        
    - name: Process valid TALM events only
      ansible.builtin.include_tasks: tasks/process_cluster_events_kubeconfig.yaml
      loop: "{{ ansible_eda.event.body }}"
      loop_control:
        label: "{{ item.cguName | default('invalid-event') }}"
      when:
        - item.eventAnnotations['cgu.openshift.io/event-type'] == "cluster"
        - item.eventAnnotations is defined # Verifies that the dictionary exists
        - item.eventAnnotations['cgu.openshift.io/cluster-name'] == item.cguName # Verifies that the key exists and compares
        - item.eventAnnotations['cgu.openshift.io/cluster-name'] is defined
        - item.eventNamespace == "ztp-install"
        - item.reason == "CguSuccess"